### PR TITLE
Update tmux default config and implement package lookup for ROS2

### PR DESCRIPTION
**Pull request by chriseichmann**
This PR fixes the tmux_default.conf for ROS2 Foxy (Kubuntu 20.04) similar to 48474c79500471874c04a84139267bd20c670388 on the master branch.  
It also implements the package lookup for translating `package://` references for ROS2 using `ament_index_python`.

This PR includes work done by @sjahr for making catmux compatible with the colcon build system.
Therefore, this PR makes #5 obsolete.

### CODE REVIEW

**Comment by fmauch** [comment]
the ROS2 branch was merged into master as I was hoping that we could get along with only one version...

**Comment by chriseichmann** [comment]
Thats not an easy task with package lookup working differently between catkin and ament

**Comment by fmauch** [comment]
I just thought about the idea of not making this a catkin/ament package anymore but plain python. the package lookup is actually not necessarily required, as instead of the `package://` functionality users can use `$(rospack find <pkgname>)/...`.

**Comment by chriseichmann** [comment]
The lookup for ROS2 is a little bit more wordy, but still do-able.

What's the work necessary to make catmux independent from ROS? Remove lookup code and adapt setup.py / remove CMakelists, right?
Maybe open an issue regarding this?

**Comment by fmauch** [comment]
Closing this in favor of #9

**Pull request closed without merging**
